/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Generate the posts manifest and copy Markdown files.
 *
 * Returns the manifest JSON string (array of `PostMetadata`).
 */
export declare function generatePostsData(postsDir: string, outputDir: string, configJson: string): string
/**
 * Generate only the posts manifest without copying Markdown files.
 *
 * Use this for dev mode where files are served directly from source.
 * Returns the manifest JSON string (array of `PostMetadata`).
 */
export declare function generatePostsManifestOnly(postsDir: string, outputDir: string, configJson: string): string
/**
 * Generate album index and per-album detail JSON files, including
 * thumbnail generation and EXIF extraction.
 *
 * Returns the albums-index JSON string.
 */
export declare function generateAlbumsData(albumsDir: string, outputDir: string, albumConfigJson: string, siteConfigJson: string): string
/**
 * Generate SEO HTML pages for every post in the manifest.
 *
 * Returns the number of pages generated.
 */
export declare function generateSeoPages(manifestJson: string, templatePath: string, outputDir: string, configJson: string): number
/** Generate `sitemap.xml`. */
export declare function generateSitemap(manifestJson: string, outputPath: string, configJson: string): void
/** Generate `rss.xml`. */
export declare function generateRss(manifestJson: string, outputPath: string, configJson: string): void
/** Generate `robots.txt`. */
export declare function generateRobots(outputPath: string, configJson: string): void
